version: '3'

volumes:
  data-mongo:

#MongoDB
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # env_file:
    #   - "../server/.env"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - data-mongo:/var/lib/mongodb
