export enum E_ResponseMessage {
  SUCCESS = 'SUCCESS',
  NOT_FOUND = 'NOT FOUND',
  ERROR = 'ERROR',
  UNPAID = 'UNPAID',
  WRONG = 'SOMETING WENT WRONG',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
